blank_issues_enabled: false
contact_links:
  - name: ğŸ“š HÃ¤ufig gestellte Fragen
    url: https://fuerthcraft.github.io/faq
    about: Schaue dir unser FAQ an, bevor du Fragen stellst.
  - name: ğŸ’¬ Community Support
    url: https://fuerthcraft.github.io/community-support
    about: Hier kannst du andere um Hilfe fragen.
  - name: ğŸ‘©â€ğŸ« FÃ¼rthCraft Wiki
    url: https://fuerthcraft.github.io/wiki
    about: Schaue dir unser FAQ an, bevor du Fragen stellst.
